services:
  db:
    image: postgres:alpine
    ports:
      - 5431:5432
    volumes:
      - postgres_data_tanstarter:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=local-db

volumes:
  postgres_data_tanstarter:
